# Generated by Django 4.2.24 on 2025-09-17 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatMessage',
            new_name='Chat',
        ),
    ]
